"""Domain models for PEEXH agent interpretation, scoring, and decisions."""

from enum import Enum
from typing import List, Literal, Optional
from pydantic import BaseModel, Field, field_validator


class ConfidenceLevel(str, Enum):
    """Discrete confidence levels determining agent action."""
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class AgentAction(str, Enum):
    """Small, explainable action set for the PEEXH agent."""
    PROPOSE_PHRASE = "PROPOSE_PHRASE"
    SHOW_CANDIDATES = "SHOW_CANDIDATES"
    REQUEST_REPEAT = "REQUEST_REPEAT"
    COMMUNICATE = "COMMUNICATE"
    LEARN_CORRECTION = "LEARN_CORRECTION"


class PhraseCandidate(BaseModel):
    """A candidate intended phrase generated by the interpreter."""
    text: str
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    explanation: Optional[str] = None


class InterpretationResult(BaseModel):
    """Structured output from speech interpretation."""
    raw_transcript: str
    stt_confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    candidates: List[PhraseCandidate] = Field(default_factory=list)


class AgentDecision(BaseModel):
    """Authoritative decision produced by PEEXH confidence scorer."""
    type: Literal["agent_decision"] = "agent_decision"
    action: AgentAction
    confidence_level: ConfidenceLevel
    overall_confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    primary_phrase: Optional[str] = None
    candidates: List[PhraseCandidate] = Field(default_factory=list)
    reason: str = ""


# --- RFC-004 Confirmation UX Models ---

class ConfirmedPhraseSource(str, Enum):
    """Source of a confirmed communication phrase."""
    PROPOSAL = "proposal"
    CANDIDATE = "candidate"
    CORRECTION = "correction"


class ConfirmProposalMessage(BaseModel):
    """Client request to confirm the primary proposed phrase."""
    type: Literal["confirm_proposal"] = "confirm_proposal"


class SelectCandidateMessage(BaseModel):
    """Client request to select one candidate from the decision list."""
    type: Literal["select_candidate"] = "select_candidate"
    phrase: str


class SubmitCorrectionMessage(BaseModel):
    """Client request to submit a manually typed or corrected phrase."""
    type: Literal["submit_correction"] = "submit_correction"
    phrase: str = Field(..., min_length=1, max_length=500)

    @field_validator("phrase")
    @classmethod
    def validate_phrase(cls, v: str) -> str:
        stripped = v.strip()
        if not stripped:
            raise ValueError("Phrase must not be empty or whitespace only")
        if len(stripped) > 500:
            raise ValueError("Phrase must not exceed 500 characters")
        return stripped


class RequestRepeatMessage(BaseModel):
    """Client request to abandon current decision and prompt to speak again."""
    type: Literal["request_repeat"] = "request_repeat"


class CommunicationReadyEvent(BaseModel):
    """Event emitted when a phrase has been verified and is ready to communicate."""
    type: Literal["communication_ready"] = "communication_ready"
    phrase: str
    source: ConfirmedPhraseSource


class RepeatRequestedEvent(BaseModel):
    """Event confirming that the active decision was cleared and repeat requested."""
    type: Literal["repeat_requested"] = "repeat_requested"
