"""Domain models for PEEXH agent interpretation, scoring, and decisions."""

from enum import Enum
from typing import List, Literal, Optional
from pydantic import BaseModel, Field


class ConfidenceLevel(str, Enum):
    """Discrete confidence levels determining agent action."""
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class AgentAction(str, Enum):
    """Small, explainable action set for the PEEXH agent."""
    PROPOSE_PHRASE = "PROPOSE_PHRASE"
    SHOW_CANDIDATES = "SHOW_CANDIDATES"
    REQUEST_REPEAT = "REQUEST_REPEAT"
    COMMUNICATE = "COMMUNICATE"
    LEARN_CORRECTION = "LEARN_CORRECTION"


class PhraseCandidate(BaseModel):
    """A candidate intended phrase generated by the interpreter."""
    text: str
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    explanation: Optional[str] = None


class InterpretationResult(BaseModel):
    """Structured output from speech interpretation."""
    raw_transcript: str
    stt_confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    candidates: List[PhraseCandidate] = Field(default_factory=list)


class AgentDecision(BaseModel):
    """Authoritative decision produced by PEEXH confidence scorer."""
    type: Literal["agent_decision"] = "agent_decision"
    action: AgentAction
    confidence_level: ConfidenceLevel
    overall_confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    primary_phrase: Optional[str] = None
    candidates: List[PhraseCandidate] = Field(default_factory=list)
    reason: str = ""
